doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            string_functions:
                to_char: App\DQL\ToChar
                cast: App\DQL\Cast
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/User/Entity'
                prefix: 'App\User\Entity'
                alias: App\User
            Auth:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/User/Authorization/System/Entity'
                prefix: 'App\User\Authorization\System\Entity'
                alias: App\User
            AuthEmail:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/User/Authorization/Email/Entity'
                prefix: 'App\User\Authorization\Email\Entity'
                alias: App\User
