# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        user:
            settings:
                index:
                    analysis:
                        analyzer:
                            user_search_analyzer:
                                type: custom
                                tokenizer: standard
                                filter:
                                    - lowercase
                                    - search_synonym
                                    - russian_morphology
                                    - english_morphology
                                    - ru_stopwords
                        filter:
                            search_synonym:
                                ignore_case: true
                                type: synonym
                                synonyms:
                                    - "пончо,накидка"
                            ru_stopwords:
                                type: stop
                                stopwords: "а,без,более,бы,был,была,были,было,быть,в,вам,вас,весь,во,вот,все,всего,всех,вы,где,да,даже,для,до,его,ее,если,есть,еще,же,за,здесь,и,из,или,им,их,к,как,ко,когда,кто,ли,либо,мне,может,мы,на,надо,наш,не,него,нее,нет,ни,них,но,ну,о,об,однако,он,она,они,оно,от,очень,по,под,при,с,со,так,также,такой,там,те,тем,то,того,тоже,той,только,том,ты,у,уже,хотя,чего,чей,чем,что,чтобы,чье,чья,эта,эти,это,я,a,an,and,are,as,at,be,but,by,for,if,in,into,is,it,no,not,of,on,or,such,that,the,their,then,there,these,they,this,to,was,will,with"
            persistence:
                driver: orm
                model: App\User\Entity\User
                provider: ~
                finder: ~
            properties:
                active: ~
                email: ~
                userData:
                    type: object
                    properties:
                        id: ~
                        nickname:
                            analyzer: user_search_analyzer
                authTokens:
                    type: object
                    properties:
                        id: ~
                        value: ~