version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/config/nginx/nginx.dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:delegated
    links:
      - php

  php:
    build:
      context: .
    volumes:
      - ./:/var/www:delegated
      - ./.docker/config/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"

  php-queue:
    build:
      dockerfile: ./.docker/config/php/php.symfony_async_worker.dockerfile
      context: .
    depends_on:
      - database
    volumes:
      - ./:/var/www:delegated
      - ./.docker/config/php/php.ini:/usr/local/etc/php/php.ini

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.docker/data/postgres/db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  elasticsearch:
    build:
      dockerfile: ./.docker/config/elastic/elasticsearch.dockerfile
      context: .
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=1gb
      - cluster.routing.allocation.disk.watermark.high=512mb
      - cluster.routing.allocation.disk.watermark.flood_stage=256mb
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./.docker/data/es:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTIC_PORT}:9200