controllers:
    resource: ../../src/Controller/
    type: annotation
api_auth:
    resource: ../../src/User/Authorization/Email/Controller/
    type: annotation
api_user_personal:
    resource: ../../src/User/Personal/Controller/
    type: annotation
api_user_admin:
    resource: ../../src/User/Admin/Controller/
    type: annotation
api_file:
    resource: ../../src/File/Storage/Local/Controller/
    type: annotation
kernel:
    resource: ../../src/Kernel.php
    type: annotation
