# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\User\Authorization\Email\Service\Notificator:
        arguments: ['%env(SITE_NAME)%']
    App\Form\Service\Notificator:
        arguments: ['%env(SITE_NAME)%', '%env(ADMIN_EMAIL_FOR_NOTIFICATIONS)%']
    App\User\Authorization\Email\Service\RedirectService:
        arguments: ['%env(ACTIVATION_LINK_SUCCESS_REDIRECT_TO)%', '%env(ACTIVATION_LINK_FAIL_REDIRECT_TO)%', '%env(RESET_PASSWORD_LINK_SUCCESS_REDIRECT_TO)%', '%env(RESET_PASSWORD_LINK_FAIL_REDIRECT_TO)%']
    App\User\Authorization\System\Security\PasswordEncoder:
        arguments: ['%env(STATIC_SALT)%']
    App\User\Authorization\System\Service\AuthService:
        arguments: ['%env(MAX_LOGIN_FAIL_COUNT)%', '%env(MAX_LOGIN_FAIL_PERIOD)%', '%env(LOGIN_FAIL_BLOCKING_TIME)%']
    App\Service\Mail\Mailer:
        arguments: ['%env(EMAIL_SEND_FROM)%']
    App\User\Authorization\System\Service\TokenService:
        arguments: ['%env(AUTH_TOKEN_LIFETIME)%']
    App\User\Authorization\Email\Service\ActivationTokenService:
        arguments: ['%env(ACTIVATION_TOKEN_LIFETIME)%']
    App\User\Authorization\Email\Service\PasswordResetTokenService:
        arguments: ['%env(PASSWORD_RESET_TOKEN_LIFETIME)%']

    # FILES
    App\File\Storage\Local\LocalFilesManager:
        arguments: ['%env(BASE_UPLOADS_DIR)%']

    App\File\Storage\Local\Controller\FileController:
        tags: ['controller.service_arguments']
        public: true
        arguments:
            - '@fos_elastica.finder.user'